version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn -b 0.0.0.0:8000 bookstore.wsgi:application"
    volumes:
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
