# Generated by Django 4.2 on 2024-04-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('favorite_books', models.ManyToManyField(related_name='favorited_by', to='store.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=my_profile.models.avatar_directory_path)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_profile.profile', verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'Profile image',
                'verbose_name_plural': 'Profile images',
                'ordering': ['pk'],
            },
        ),
    ]
